---
title: "Capitulo 6"
author: "Cesar Zamora"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Paquetes para el analisis
library(haven)
library(tidyverse)
library(matlib)
library("Matrix")
data <- read_sav("chapter.6.sav")
```

## Ejercicio 6.7.1 page 183

**Código original**

```{r eval=FALSE}
* Encoding: UTF-8.
MATRIX./*6-7-1 page 183.
get y/variable y1,y2,y3,y4/missing=omit.
get y1/variable y11,y12,y13,y14/missing=omit.
get y2/variable y21,y22,y23,y24/missing=omit.
get y3/variable y31,y32,y33,y34/missing=omit.
get y4/variable y41,y42,y43,y44/missing=omit.
get y5/variable y51,y52,y53,y54/missing=omit.
get y6/variable y61,y62,y63,y64/missing=omit.
COMPUTE n=nrow(y).
COMPUTE onev=make(n,1,1).
COMPUTE onem=make(n,n,1).
COMPUTE i=ident(n).
COMPUTE n1=nrow(y1).
COMPUTE onev1=make(n1,1,1).
COMPUTE onem1=make(n1,n1,1).
COMPUTE i1=ident(n1).
COMPUTE n2=nrow(y2).
COMPUTE onev2=make(n2,1,1).
COMPUTE onem2=make(n2,n2,1).
COMPUTE i2=ident(n2).
COMPUTE n3=nrow(y3).
COMPUTE onev3=make(n3,1,1).
COMPUTE onem3=make(n3,n3,1).
COMPUTE i3=ident(n3).
COMPUTE n4=nrow(y4).
COMPUTE onev4=make(n4,1,1).
COMPUTE onem4=make(n4,n4,1).
COMPUTE i4=ident(n4).
COMPUTE n5=nrow(y5).
COMPUTE onev5=make(n5,1,1).
COMPUTE onem5=make(n5,n5,1).
COMPUTE i5=ident(n5).
COMPUTE n6=nrow(y6).
COMPUTE onev6=make(n6,1,1).
COMPUTE onem6=make(n6,n6,1).
COMPUTE i6=ident(n6).
COMPUTE m1=t(y1)*onev1/n1.
COMPUTE m2=t(y2)*onev2/n2.
COMPUTE m3=t(y3)*onev3/n3.
COMPUTE m4=t(y4)*onev4/n4.
COMPUTE m5=t(y5)*onev5/n5.
COMPUTE m6=t(y6)*onev6/n6.
COMPUTE s=t(y)*(i-onem/n)*y/(n-1).
COMPUTE s1=t(y1)*(i1-onem1/n1)*y1/(n1-1).
COMPUTE s2=t(y2)*(i2-onem2/n2)*y2/(n2-1).
COMPUTE s3=t(y3)*(i3-onem3/n3)*y3/(n3-1).
COMPUTE s4=t(y4)*(i4-onem4/n4)*y4/(n4-1).
COMPUTE s5=t(y5)*(i5-onem5/n5)*y5/(n5-1).
COMPUTE s6=t(y6)*(i6-onem6/n6)*y6/(n6-1).
COMPUTE mt=(48-1)*s.
COMPUTE me=7*(s1+s2+s3+s4+s5+s6).
COMPUTE mh=mt-me.
COMPUTE lambda=det(me)/(det(mh+me)).
COMPUTE u=chol(me).
COMPUTE landa=inv(t(u))*mh*inv(u).
call eigen(landa,eigenv,eigenval).
COMPUTE Us=msum(eigenval).
COMPUTE USTAT=42*Us/5.
COMPUTE vs=msum(eigenval/(1+eigenval)).
COMPUTE teta=eigenval(1)/(1+eigenval(1)).
PRINT m1.
PRINT m2.
PRINT m3.
PRINT m4.
PRINT m5.
PRINT m6.
PRINT s.
PRINT s1.
PRINT s2.
PRINT s3.
PRINT s4.
PRINT me.
PRINT mt.
PRINT mh.
PRINT lambda.
PRINT landa.
PRINT eigenval.
PRINT US.
PRINT USTAT.
PRINT vs.
PRINT teta.
end matrix.
```

**Traducción del código a R**



```{r }
# selecionamos columnas omitiendo NA
y <- data %>% select(Y1,Y2,Y3,Y4) %>% drop_na() %>% as.matrix()
y1 <- data %>% select(y11,y12,y13,y14) %>% drop_na() %>% as.matrix()
y2 <- data %>% select(y21,y22,y23,y24) %>% drop_na() %>% as.matrix()
y3 <- data %>% select(y31,y32,y33,y34) %>% drop_na() %>% as.matrix()
y4 <- data %>% select(y41,y42,y43,y44) %>% drop_na() %>% as.matrix()
y5 <- data %>% select(y51,y52,y53,y54) %>% drop_na() %>% as.matrix()
y6 <- data %>% select(y61,y62,y63,y64) %>% drop_na() %>% as.matrix()

# contadores
n=nrow(y)
n1=nrow(y1)
n2=nrow(y2)
n3=nrow(y3)
n4=nrow(y4)
n5=nrow(y5)
n6=nrow(y6)

# Matrices y vectores de 1s
onev <- matrix(1, n,1)
onem <- matrix(1, n,n)
onev1 <- matrix(1, n1,1)
onem1 <- matrix(1, n1,n1)
onev2 <- matrix(1, n2,1)
onem2 <- matrix(1, n2,n2)
onev3 <- matrix(1, n3,1)
onem3 <- matrix(1, n3,n3)
onev4 <- matrix(1, n4,1)
onem4 <- matrix(1, n4,n4)
onev5 <- matrix(1, n5,1)
onem5 <- matrix(1, n5,n5)
onev6 <- matrix(1, n6,1)
onem6 <- matrix(1, n6,n6)

## Matrices identidad
i <- diag(n)
i1 <- diag(n1)
i2 <- diag(n2)
i3 <- diag(n3)
i4 <- diag(n4)
i5 <- diag(n5)
i6 <- diag(n6)

## Vectores de medias
m1 <- t(y1)%*%onev1/n1
m2 <- t(y1)%*%onev1/n2
m3 <- t(y1)%*%onev1/n3
m4 <- t(y1)%*%onev1/n4
m5 <- t(y1)%*%onev1/n5
m6 <- t(y1)%*%onev1/n6

# Vectores de covarianzas
s <- t(y)%*%(i-onem/n)%*%y/(n-1)
s1 <- t(y1)%*%(i1-onem1/n1)%*%y1/(n1-1)
s2 <- t(y2)%*%(i2-onem1/n2)%*%y2/(n2-1)
s3 <- t(y3)%*%(i3-onem1/n3)%*%y3/(n3-1)
s4 <- t(y4)%*%(i4-onem1/n4)%*%y4/(n4-1)
s5 <- t(y5)%*%(i5-onem1/n5)%*%y5/(n5-1)
s6 <- t(y6)%*%(i6-onem1/n6)%*%y6/(n6-1)

# Estimadores
mt=(48-1)*s
me=7*(s1+s2+s3+s4+s5+s6)
mh=mt-me
lambda=det(me)/(det(mh+me))
u=chol(me)
landa=inv(t(u))*mh*inv(u)
em <- eigen(landa)
eigenv <- em$vect
eigenval <- em$values
Us=sum(eigenval)
USTAT=42*Us/5
vs=sum(eigenval/(1+eigenval))
teta=max(eigenval)/(1+max(eigenval))

# Imprimimos valores
m1
m2
m3
m4
m5
m6
s
s1
s2
s3
s4
me
mt
mh
lambda
landa
eigenval
Us
USTAT
vs
teta

```

## Ejercicio 6.8.1 page 188

**Código original**

```{r eval=FALSE}
MATRIX./*6-8-1 page 188.
get y/variable y1,y2,y3,y4/missing=omit.
get y1/variable y11,y12,y13,y14/missing=omit.
get y2/variable y21,y22,y23,y24/missing=omit.
get y3/variable y31,y32,y33,y34/missing=omit.
get y4/variable y41,y42,y43,y44/missing=omit.
get y5/variable y51,y52,y53,y54/missing=omit.
get y6/variable y61,y62,y63,y64/missing=omit.
COMPUTE n=nrow(y).
COMPUTE onev=make(n,1,1).
COMPUTE onem=make(n,n,1).
COMPUTE i=ident(n).
COMPUTE n1=nrow(y1).
COMPUTE onev1=make(n1,1,1).
COMPUTE onem1=make(n1,n1,1).
COMPUTE i1=ident(n1).
COMPUTE n2=nrow(y2).
COMPUTE onev2=make(n2,1,1).
COMPUTE onem2=make(n2,n2,1).
COMPUTE i2=ident(n2).
COMPUTE n3=nrow(y3).
COMPUTE onev3=make(n3,1,1).
COMPUTE onem3=make(n3,n3,1).
COMPUTE i3=ident(n3).
COMPUTE n4=nrow(y4).
COMPUTE onev4=make(n4,1,1).
COMPUTE onem4=make(n4,n4,1).
COMPUTE i4=ident(n4).
COMPUTE n5=nrow(y5).
COMPUTE onev5=make(n5,1,1).
COMPUTE onem5=make(n5,n5,1).
COMPUTE i5=ident(n5).
COMPUTE n6=nrow(y6).
COMPUTE onev6=make(n6,1,1).
COMPUTE onem6=make(n6,n6,1).
COMPUTE i6=ident(n6).
COMPUTE m1=t(y1)*onev1/n1.
COMPUTE m2=t(y2)*onev2/n2.
COMPUTE m3=t(y3)*onev3/n3.
COMPUTE m4=t(y4)*onev4/n4.
COMPUTE m5=t(y5)*onev5/n5.
COMPUTE m6=t(y6)*onev6/n6.
COMPUTE s=t(y)*(i-onem/n)*y/(n-1).
COMPUTE s1=t(y1)*(i1-onem1/n1)*y1/(n1-1).
COMPUTE s2=t(y2)*(i2-onem2/n2)*y2/(n2-1).
COMPUTE s3=t(y3)*(i3-onem3/n3)*y3/(n3-1).
COMPUTE s4=t(y4)*(i4-onem4/n4)*y4/(n4-1).
COMPUTE s5=t(y5)*(i5-onem5/n5)*y5/(n5-1).
COMPUTE s6=t(y6)*(i6-onem6/n6)*y6/(n6-1).
COMPUTE mt=(48-1)*s.
COMPUTE me=7*(s1+s2+s3+s4+s5+s6).
COMPUTE mh=mt-me.
COMPUTE lambda=det(me)/(det(mh+me)).
COMPUTE u=chol(me).
COMPUTE landa=inv(t(u))*mh*inv(u).
call eigen(landa,eigenv,eigenval).
COMPUTE Us=msum(eigenval).
COMPUTE USTAT=42*Us/5.
COMPUTE vs=msum(eigenval/(1+eigenval)).
COMPUTE teta=eigenval(1)/(1+eigenval(1)).
COMPUTE slambda=1-lambda.
COMPUTE steta=teta.
COMPUTE s2lambda=1-lambda**(1/4).
COMPUTE svs=vs/4.
COMPUTE sus=(us/4)/(1+(us/4)).
PRINT slambda.
PRINT steta.
PRINT s2lambda.
PRINT svs.
PRINT sus.
end matrix.
```


**Traducción del código a R**



```{r }
# selecionamos columnas omitiendo NA
y <- data %>% select(Y1,Y2,Y3,Y4) %>% drop_na() %>% as.matrix()
y1 <- data %>% select(y11,y12,y13,y14) %>% drop_na() %>% as.matrix()
y2 <- data %>% select(y21,y22,y23,y24) %>% drop_na() %>% as.matrix()
y3 <- data %>% select(y31,y32,y33,y34) %>% drop_na() %>% as.matrix()
y4 <- data %>% select(y41,y42,y43,y44) %>% drop_na() %>% as.matrix()
y5 <- data %>% select(y51,y52,y53,y54) %>% drop_na() %>% as.matrix()
y6 <- data %>% select(y61,y62,y63,y64) %>% drop_na() %>% as.matrix()

# contadores
n=nrow(y)
n1=nrow(y1)
n2=nrow(y2)
n3=nrow(y3)
n4=nrow(y4)
n5=nrow(y5)
n6=nrow(y6)

# Matrices y vectores de 1s
onev <- matrix(1, n,1)
onem <- matrix(1, n,n)
onev1 <- matrix(1, n1,1)
onem1 <- matrix(1, n1,n1)
onev2 <- matrix(1, n2,1)
onem2 <- matrix(1, n2,n2)
onev3 <- matrix(1, n3,1)
onem3 <- matrix(1, n3,n3)
onev4 <- matrix(1, n4,1)
onem4 <- matrix(1, n4,n4)
onev5 <- matrix(1, n5,1)
onem5 <- matrix(1, n5,n5)
onev6 <- matrix(1, n6,1)
onem6 <- matrix(1, n6,n6)

## Matrices identidad
i <- diag(n)
i1 <- diag(n1)
i2 <- diag(n2)
i3 <- diag(n3)
i4 <- diag(n4)
i5 <- diag(n5)
i6 <- diag(n6)

## Vectores de medias
m1 <- t(y1)%*%onev1/n1
m2 <- t(y1)%*%onev1/n2
m3 <- t(y1)%*%onev1/n3
m4 <- t(y1)%*%onev1/n4
m5 <- t(y1)%*%onev1/n5
m6 <- t(y1)%*%onev1/n6

# Vectores de covarianzas
s <- t(y)%*%(i-onem/n)%*%y/(n-1)
s1 <- t(y1)%*%(i1-onem1/n1)%*%y1/(n1-1)
s2 <- t(y2)%*%(i2-onem1/n2)%*%y2/(n2-1)
s3 <- t(y3)%*%(i3-onem1/n3)%*%y3/(n3-1)
s4 <- t(y4)%*%(i4-onem1/n4)%*%y4/(n4-1)
s5 <- t(y5)%*%(i5-onem1/n5)%*%y5/(n5-1)
s6 <- t(y6)%*%(i6-onem1/n6)%*%y6/(n6-1)

# Estimadores
mt=(48-1)*s
me=7*(s1+s2+s3+s4+s5+s6)
mh=mt-me
lambda=det(me)/(det(mh+me))
u=chol(me)
landa=inv(t(u))*mh*inv(u)
em <- eigen(landa)
eigenv <- em$vect
eigenval <- em$values
Us <- sum(eigenval)
USTAT <- 42*Us/5
vs <- sum(eigenval/(1+eigenval))
teta <- max(eigenval)/(1+max(eigenval))
slambda <- 1-lambda
steta <- teta
s2lambda <- 1-lambda**(1/4)
svs <- vs/4
sus <- (Us/4)/(1+(Us/4))

# Imprimimos valores
slambda
steta
s2lambda
svs
sus
```


## Ejercicio 2.3.6 page 235

**Código original**

```{r eval=FALSE}
MATRIX./*2-3-6 page 235.
get y/variable y1,y2,y3,y4/missing=omit.
get y1/variable y11,y12,y13,y14/missing=omit.
get y2/variable y21,y22,y23,y24/missing=omit.
get y3/variable y31,y32,y33,y34/missing=omit.
get y4/variable y41,y42,y43,y44/missing=omit.
get y5/variable y51,y52,y53,y54/missing=omit.
get y6/variable y61,y62,y63,y64/missing=omit.
COMPUTE n=nrow(y).
COMPUTE onev=make(n,1,1).
COMPUTE onem=make(n,n,1).
COMPUTE i=ident(n).
COMPUTE n1=nrow(y1).
COMPUTE onev1=make(n1,1,1).
COMPUTE onem1=make(n1,n1,1).
COMPUTE i1=ident(n1).
COMPUTE n2=nrow(y2).
COMPUTE onev2=make(n2,1,1).
COMPUTE onem2=make(n2,n2,1).
COMPUTE i2=ident(n2).
COMPUTE n3=nrow(y3).
COMPUTE onev3=make(n3,1,1).
COMPUTE onem3=make(n3,n3,1).
COMPUTE i3=ident(n3).
COMPUTE n4=nrow(y4).
COMPUTE onev4=make(n4,1,1).
COMPUTE onem4=make(n4,n4,1).
COMPUTE i4=ident(n4).
COMPUTE n5=nrow(y5).
COMPUTE onev5=make(n5,1,1).
COMPUTE onem5=make(n5,n5,1).
COMPUTE i5=ident(n5).
COMPUTE n6=nrow(y6).
COMPUTE onev6=make(n6,1,1).
COMPUTE onem6=make(n6,n6,1).
COMPUTE i6=ident(n6).
COMPUTE s=t(y)*(i-onem/n)*y/(n-1).
COMPUTE s1=t(y1)*(i1-onem1/n1)*y1/(n1-1).
COMPUTE s2=t(y2)*(i2-onem2/n2)*y2/(n2-1).
COMPUTE s3=t(y3)*(i3-onem3/n3)*y3/(n3-1).
COMPUTE s4=t(y4)*(i4-onem4/n4)*y4/(n4-1).
COMPUTE s5=t(y5)*(i5-onem5/n5)*y5/(n5-1).
COMPUTE s6=t(y6)*(i6-onem6/n6)*y6/(n6-1).
COMPUTE mt=(48-1)*s.
COMPUTE me=7*(s1+s2+s3+s4+s5+s6).
COMPUTE bc1={2;-1;-1;-1;-1;2}.
COMPUTE y1bar=t(y1)*onev1/n1.
COMPUTE y2bar=t(y2)*onev2/n2.
COMPUTE y3bar=t(y3)*onev3/n3.
COMPUTE y4bar=t(y4)*onev4/n4.
COMPUTE y5bar=t(y5)*onev5/n5.
COMPUTE y6bar=t(y6)*onev6/n6.
PRINT y1bar.
PRINT y2bar.
PRINT y3bar.
PRINT y4bar.
PRINT y5bar.
PRINT y6bar.
COMPUTE ybarha={y1bar,y2bar,y3bar,y4bar,y5bar,y6bar}.
PRINT ybarha.
COMPUTE a1=8/(t(bc1)*bc1).
PRINT a1.
COMPUTE b1=ybarha*bc1.
PRINT b1.
COMPUTE h1=a1*b1*t(b1).
PRINT h1.
COMPUTE rankh1=rank(h1).
PRINT rankh1.
COMPUTE bc2={1;0;0;0;0;-1}.
COMPUTE a2=8/(t(bc2)*bc2).
COMPUTE b2=ybarha*bc2.
COMPUTE h2=a2*b2*t(b2).
PRINT h2.
COMPUTE habmda1=det(me)/(det(me+h1)).
COMPUTE habmda2=det(me)/(det(me+h2)).
PRINT habmda1.
PRINT habmda2.
end matrix.
```

**Traducción del código a R**



```{r }
# selecionamos columnas omitiendo NA
y <- data %>% select(Y1,Y2,Y3,Y4) %>% drop_na() %>% as.matrix()
y1 <- data %>% select(y11,y12,y13,y14) %>% drop_na() %>% as.matrix()
y2 <- data %>% select(y21,y22,y23,y24) %>% drop_na() %>% as.matrix()
y3 <- data %>% select(y31,y32,y33,y34) %>% drop_na() %>% as.matrix()
y4 <- data %>% select(y41,y42,y43,y44) %>% drop_na() %>% as.matrix()
y5 <- data %>% select(y51,y52,y53,y54) %>% drop_na() %>% as.matrix()
y6 <- data %>% select(y61,y62,y63,y64) %>% drop_na() %>% as.matrix()

# contadores
n=nrow(y)
n1=nrow(y1)
n2=nrow(y2)
n3=nrow(y3)
n4=nrow(y4)
n5=nrow(y5)
n6=nrow(y6)

# Matrices y vectores de 1s
onev <- matrix(1, n,1)
onem <- matrix(1, n,n)
onev1 <- matrix(1, n1,1)
onem1 <- matrix(1, n1,n1)
onev2 <- matrix(1, n2,1)
onem2 <- matrix(1, n2,n2)
onev3 <- matrix(1, n3,1)
onem3 <- matrix(1, n3,n3)
onev4 <- matrix(1, n4,1)
onem4 <- matrix(1, n4,n4)
onev5 <- matrix(1, n5,1)
onem5 <- matrix(1, n5,n5)
onev6 <- matrix(1, n6,1)
onem6 <- matrix(1, n6,n6)

## Matrices identidad
i <- diag(n)
i1 <- diag(n1)
i2 <- diag(n2)
i3 <- diag(n3)
i4 <- diag(n4)
i5 <- diag(n5)
i6 <- diag(n6)

## Vectores de medias
m1 <- t(y1)%*%onev1/n1
m2 <- t(y1)%*%onev1/n2
m3 <- t(y1)%*%onev1/n3
m4 <- t(y1)%*%onev1/n4
m5 <- t(y1)%*%onev1/n5
m6 <- t(y1)%*%onev1/n6

# Vectores de covarianzas
s <- t(y)%*%(i-onem/n)%*%y/(n-1)
s1 <- t(y1)%*%(i1-onem1/n1)%*%y1/(n1-1)
s2 <- t(y2)%*%(i2-onem1/n2)%*%y2/(n2-1)
s3 <- t(y3)%*%(i3-onem1/n3)%*%y3/(n3-1)
s4 <- t(y4)%*%(i4-onem1/n4)%*%y4/(n4-1)
s5 <- t(y5)%*%(i5-onem1/n5)%*%y5/(n5-1)
s6 <- t(y6)%*%(i6-onem1/n6)%*%y6/(n6-1)

# Estimadores
mt=(48-1)*s
me=7*(s1+s2+s3+s4+s5+s6)

#Otro
bc1=rbind(c(2),c(-1),c(-1),c(-1),c(-1),c(2))

# Vectores de medias
y1bar <- t(y1)%*%onev1/n1
y2bar <- t(y2)%*%onev2/n2
y3bar <- t(y3)%*%onev3/n3
y4bar <- t(y4)%*%onev4/n4
y5bar <- t(y5)%*%onev5/n5
y6bar <- t(y6)%*%onev6/n6

# Imprimimos vectores de medias
y1bar
y2bar
y3bar
y4bar
y5bar
y6bar

# vector de medias
ybarha <- cbind(y1bar,y2bar,y3bar,y4bar,y5bar,y6bar)
ybarha

# Otros estimadores
a1=8/(t(bc1)%*%bc1)
a1

b1=ybarha%*%bc1
b1

h1=a1[1,1]*(b1%*%t(b1))
h1

rankh1=rankMatrix(h1)
rankh1[1]

bc2=rbind(c(1),c(0),c(0),c(0),c(0),c(-1))

a2=8/(t(bc2)%*%bc2)

b2=ybarha%*%bc2

h2=a2[1,1]*b2%*%t(b2)
h2

habmda1=det(me)/(det(me+h1))
habmda2=det(me)/(det(me+h2))
habmda1
habmda2

```
